spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: test
    password: test

  jpa:
    hibernate.ddl-auto: none # Flyway is creating the table
    show-sql: true
    properties:
      hibernate:
        format_sql: true

