[versions]
mockito-version = "5.18.0"

# plugins
spring-boot-version = "3.5.3"
spring-dependency-management-version = "1.1.7"
freefair-lombok-version = "8.14"

[libraries]
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito-version" }

[plugins]
springframework-boot = { id = "org.springframework.boot", version.ref = "spring-boot-version" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management-version" }
freefair-lombok = { id = "io.freefair.lombok", version.ref = "freefair-lombok-version" }
